COPY    START  1000
FIRST1  LDA    BETA1
ADDLP1  ADD    BETA1,X
EOF1    BYTE   C'EOF'
INPUT1  BYTE   X'05'
        LDA    BETA1,X
        STA    GAMMA1,X
        LDX    INDEX1
        COMP   K1
        JLT    ADDLP1
BETA1   RESW   2
GAMMA1  RESW   1
K1      WORD   1
INDEX1  WORD   0
        END
