MID2		START	0
	FIRST		BASE	BUFEND
   			LDB	#BUFEND
			+LDA   #TEMP
			LDA    RETADD,X
			LDT	VALUE,X
			TD	=X’1F’
TEMP1		RESW	1
			LDX   	TEMP1
			USE	CBLKS
	BUFFER		RESB	4096
			ORG 	BUFFER
	SYMBOL		RESB	7
	VALUE		RESW	1
	TAG		RESW	2
			ORG	BUFFER+4096
	BUFEND		EQU	*
			USE	CDATA
	RETADD		RESW 	3
			USE    CBLKS
			LDT	=X’FEFC35’
			USE	CDATA
	TEMP		EQU 	BUFEND–BUFFER
	FLAG		RESB	2
LTORG
+LDX	=X’FFFFFE’
USE	
			J	@ RETADD
			+LDX   FLAG
	TAB		BYTE	X’ABABAB’
			END	FIRST
